'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Categoria.vb
''  Implementation of the Class BE.Categoria
''  Generated by Enterprise Architect
''  Created on:      16-Oct-2017 12:11:08 PM
''  Original author: daniel.baubeta
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



	Public Class Categoria
		Inherits ABM


		Private _Cliente As BE.Cliente
    Private _IDReal As String
		
		Public Property Cliente() As BE.Cliente
			Get
				Return _Cliente
			End Get
			Set(ByVal Value as BE.Cliente)
				_Cliente = Value
			End Set
		End Property

		Public Property ID_Categoria_Real() As String
			Get
            Return _IDReal
			End Get
			Set(ByVal Value as String)
            _IDReal = Value
			End Set
		End Property


	End Class
