'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Enterprise

    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''mnuButtonTablas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuButtonTablas As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''noTranslateListaTablas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noTranslateListaTablas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuButtonSecuencias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuButtonSecuencias As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''noTranslateListaSecuencias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noTranslateListaSecuencias As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuButtonReportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuButtonReportes As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''noTranslateListaReportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noTranslateListaReportes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuButtonConcursos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuButtonConcursos As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''noTranslateListaConcursos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noTranslateListaConcursos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuButtonIdioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuButtonIdioma As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''noTranslateListaIdiomas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noTranslateListaIdiomas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuButtonSeguridad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuButtonSeguridad As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''noTranslateListaSeguridad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noTranslateListaSeguridad As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuButtonLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuButtonLogout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dlIdiomas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlIdiomas As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
