'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TransmisionesLista
    
    '''<summary>
    '''ImagenSiNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImagenSiNo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''noTranslateModalMessageSiNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noTranslateModalMessageSiNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnModalSi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalSi As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnModalNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ImagenMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImagenMensaje As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''noTranslateModalMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noTranslateModalMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnModalOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalOk As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblTransmisionesListaTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransmisionesListaTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCliente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dlClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlClientes As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dlmes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlmes As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dlano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlano As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''grdTransmisioness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTransmisioness As Global.System.Web.UI.WebControls.GridView
End Class
